### ISSUE TITLE
Scripts Have Windows Line Endings

### ISSUE THREAD

**Issue by opticyclic** [b180tech/cordaptor#4]
The scripts don't start on linux because they use Windows file endings:

    ./cordaptor.sh
    bash: ./cordaptor.sh: /bin/sh^M: bad interpreter: No such file or directory
    
    file cordaptor.sh
    cordaptor.sh: POSIX shell script, ASCII text executable, with CRLF line terminators

**Comment by igor-b180** [comment]
Hi @opticyclic, thank you for raising this.
Please could you confirm what exactly are you running, docker image or standalone version?

**Comment by opticyclic** [comment]
Standalone

**Comment by igor-b180** [comment]
We are going to change the build process to prevent this issue from arising in future, but in the meantime tar file in the 0.1.0 distribution with this problem fixed was re-uploaded
